### ISSUE TITLE
Assetion fail + Renderer errors

### ISSUE THREAD

**Issue by noorbeast** [createthis/createthis_vr_ui#1]
I get the following errors, the Assertion failed while running and the renderer errors when closed, Unity 5.6.1f1 and 5.6.0 EditorVRp3:

Assertion failed on expression: 'IsMatrixValid(matrix)'

Instantiating material due to calling renderer.material during edit mode. This will leak materials into the scene. You most likely want to use renderer.sharedMaterial instead.
UnityEngine.Renderer:get_materials()
CreateThis.VR.UI.Interact.Selectable:UpdateMaterialMeshRendererNoSelectableController(GameObject, Boolean) (at Assets/CreateThis/Scripts/VR/UI/Interact/Selectable.cs:76)
CreateThis.VR.UI.Interact.Selectable:UpdateMaterialNoSelectableController(GameObject, Boolean) (at Assets/CreateThis/Scripts/VR/UI/Interact/Selectable.cs:124)
CreateThis.VR.UI.Interact.Selectable:SetSelected(Boolean) (at Assets/CreateThis/Scripts/VR/UI/Interact/Selectable.cs:196)
CreateThis.VR.UI.Interact.Selectable:SetStickySelected(Boolean) (at Assets/CreateThis/Scripts/VR/UI/Interact/Selectable.cs:169)
CreateThis.VR.UI.Button.SkyboxButton:SkyboxChanged() (at Assets/CreateThis/Scripts/Example/SkyboxButton.cs:25)
CreateThis.VR.UI.Button.SkyboxButton:Start() (at Assets/CreateThis/Scripts/Example/SkyboxButton.cs:35)

**Comment by createthis** [comment]
> Assertion failed on expression: 'IsMatrixValid(matrix)'

This is caused by the script on the UseOpenVR object in the non VRTK scene. Possible solutions:
- Deactivate that object and don't switch to the VRTK scene unless you want to fix Settings -> Player -> VR SDKs.
- Delete that object and turn off the auto detect code in the VRTK scene.
- Ignore it (I don't think it hurts anything).

> Instantiating material due to calling renderer.material during edit mode. This will leak materials into the scene. You most likely want to use renderer.sharedMaterial instead.

This was introduced just yesterday or the day before, if I remember correctly. It's only triggered by the example SkyBoxButton, so if you don't use that in your own code you can safely ignore it.

**Comment by noorbeast** [comment]
That resolves those issues, much appreciated.

**Comment by createthis** [comment]
I had some time this morning, so these errors have been corrected.

**Comment by noorbeast** [comment]
Awesome stuff!
